import { Signika } from "next/font/google";
import "./global.css";
import { Header } from "../components/layout/header.js";

const signika = Signika({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={signika.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
